### ISSUE TITLE
Broken with SLS FW 2.36.0 due to `servicePath` missing

### ISSUE THREAD

**Issue by jthomas** [fernando-mc/serverless-finch#116]
This is a:

* [X] Bug report

---

For bug reports:

### Expected behavior

I cannot `sls client deploy` with the new release of the framework (2.36.0). It gives me this error:

```

 Type Error ----------------------------------------------

  TypeError: e.join is not a function
      at Client._validateConfig (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:56:76)
      at Client._processDeployment (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:136:17)
      at Object.client:deploy:deploy [as hook] (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:44:21)
      at PluginManager.invoke (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/classes/PluginManager.js:552:20)
      at PluginManager.run (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/classes/PluginManager.js:598:18)
      at async Serverless.run (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/Serverless.js:312:5)
      at async /Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/scripts/serverless.js:612:9

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

Digging through the code to find out what's going wrong - the actual error is coming from here:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at Object.join (node:path:1081:7)
    at validateClient (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/lib/validate.js:18:27)
    at Client._validateConfig (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:54:7)
    at Client._processDeployment (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:137:17)
    at Object.client:deploy:deploy [as hook] (/Users/jamesthomas/code/github/bakedin/gift_subscriptions/node_modules/serverless-finch/index.js:44:21)
    at PluginManager.invoke (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/classes/PluginManager.js:552:20)
    at PluginManager.run (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/classes/PluginManager.js:598:18)
    at async Serverless.run (/Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/lib/Serverless.js:312:5)
    at async /Users/jamesthomas/.nvm/versions/node/v15.5.1/lib/node_modules/serverless/scripts/serverless.js:612:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

Looking at the line:
```javascript
 const clientPath = path.join(serverless.config.servicePath, distributionFolder);
```

`serverless.config.servicePath` is not set. Looking at the release notes - it seems the value should be replaced by "serviceDir". 

https://github.com/serverless/serverless/releases/tag/v2.36.0

If I manually update the two references to that variable in the project - it works again
https://github.com/fernando-mc/serverless-finch/search?q=servicePath

**Comment by jthomas** [comment]
Looks like they fixed the bug in the framework - so this is no longer an issue.
https://github.com/serverless/serverless/pull/9343
