### ISSUE TITLE
Error deploying website: TypeError: this.aws.request(...).bind is not a function

### ISSUE THREAD

**Issue by celtric** [fernando-mc/serverless-finch#118]
This is a:

* [ ] Feature request or change
* [x] Bug report

---

For bug reports:

### Expected behavior

Website is deployed successfully.

### Actual behavior

Deployment fails with the following output:

```
Serverless: Deploying client to stage "REDACTED" in region "eu-west-1"...

 Type Error ----------------------------------------------

  TypeError: this.aws.request(...).bind is not a function
      at Client.listBuckets (REDACTED\node_modules\serverless-finch\index.js:80:79)
      at Client._processDeployment (REDACTED\node_modules\serverless-finch\index.js:274:17)
      at tryCatcher (REDACTED\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (REDACTED\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (REDACTED\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (REDACTED\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (REDACTED\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (REDACTED\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (REDACTED\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (REDACTED\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21)

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              16.10.0
     Framework Version:         2.62.0
     Plugin Version:            5.4.6
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

### Steps to reproduce

* **Operating system:** Windows 11
* **serverless-finch version:** 1.4.0
* `serverless.yml` **that produces bug:** standard one based on examples
* **Command that produces bug:** default one defined in documentation
* **Other details:**

When logging `this.aws.request`, the following output is returned: `[AsyncFunction: request]`.

**Comment by celtric** [comment]
Sorry, after debugging the code I've realized that we were on the latest version... of the 1.x branch 🤦🏻 Upgrading to `2.6.0` solved the issue.
