### ISSUE TITLE
After upgrade to 2.0: ServerlessError: ReferenceError: index is not defined

### ISSUE THREAD

**Issue by wzedi** [fernando-mc/serverless-finch#47]
This is a:

* [] Feature request or change
* [x] Bug report

---

For bug reports:

### Expected behavior
Running `serverless client deploy` my static site should be deployed to S3ˀ

### Actual behavior
After upgrade to 2.0 I get the following error when running `SLS_DEBUG=true serverless client deploy`:

```
ServerlessError: ReferenceError: index is not defined
    at _validateConfig.then.then.catch.error (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless-finch/index.js:223:33)
From previous event:
    at Client._processDeployment (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless-finch/index.js:222:13)
    at Object.client:deploy:deploy [as hook] (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless-finch/index.js:45:14)
    at BbPromise.reduce (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/warrick/dev/orchestrated/people-mapper-ui/node_modules/serverless/bin/serverless:42:50)
```

### Steps to reproduce

1. Upgrade to 2.0 
1. include WebsiteConfiguration with IndexDocument or ErrorDocument or both
1. run serverless client deploy

* **Operating system:**
Mac OSX

* **serverless-finch version:**
2.0

* `serverless.yml` **that produces bug:**
Any serverless yml with WebsiteConfiguration IndexDocument and ErrorDocument will produce this error.

* **Command that produces bug:**
serverless client deploy

* **Other details:**
This error is reported immediately after an upgrade to serverless-finch 2.0.
See lines 127 and 128 in index.js:
        indexDoc = this.options.indexDocument || index.html;
        errorDoc = this.options.errorDocument || error.html;

I think the default values should be explicit strings to fix this issue.

**Comment by fernando-mc** [comment]
@wzedi merged. Cutting a new release for this in v2.0.1. Should be live in a few minutes.

**Comment by fernando-mc** [comment]
cc @linusmarco in case you need to pull this into anything you're working on.

**Comment by fernando-mc** [comment]
@wzedi this is live. Please feel free to reopen if this doesn't fix the issue!

**Comment by linusmarco** [comment]
Sorry about this, guys! Thanks @wzedi and @fernando-mc for turning around the fix so quickly!

**Comment by fernando-mc** [comment]
@linusmarco no worries. I missed it too and didn't have tests set up for it. 

@wzedi Before I forget - I'll add you as a contributor. Thanks for the quick PR.

**Comment by wzedi** [comment]
Tested this and all working well. Thanks guys for quick turn around.

Question:

Installed v 2.0.1 and ran sls client deploy with objectHeaders set. The deployment runs as expected and the object headers are set as expected. Excellent. Thanks guys.

Question for this feature request is the deployment has a confirmation prompt:
`Do you want to proceed?`

This waits for user input. I tested this from my local environment and had no problems replying to the prompt. However if I run this from a CI pipeline, say CircleCI, would that prompt stall the build?

**Comment by wzedi** [comment]
If it will stall is it possible to provide a CLI switch to disable prompts for automated deployments?
